spring: 
    profiles: 
        active: 
        - dev
---
spring: 
    profiles: dev   #开发环境
    application: 
        name: microservicecloud2-config-demo-dev
---
spring: 
    profiles: test  #测试环境
    application: 
        name: microservicecloud2-config-demo-test
#   请保存为UTF-8格式